"""TABenchmark: a shared benchmark for 50 years of traffic assignment models.

See docs/ARCHITECTURE.md for the design and docs/REFERENCES.md for the
verified reference canon this benchmark implements.
"""

from .core import (
    Budget,
    BudgetCoords,
    Capabilities,
    ContaminationError,
    Demand,
    ElasticDemand,
    FactorSpec,
    FlowState,
    Network,
    ReferenceSolution,
    ResultBundle,
    RngBundle,
    Scenario,
    Trace,
)
from .data import (
    braess_scenario,
    elastic_two_route_scenario,
    load_scenario,
    two_route_scenario,
)
from .estimation import (
    ESTIMATOR_REGISTRY,
    CallableEstimator,
    EstimationTask,
    GLSEstimator,
    ODEstimator,
    ODResultBundle,
    ODState,
    ODTrace,
    PriorBaseline,
    SpiessEstimator,
    SPSAEstimator,
    VZWEntropyEstimator,
    register_estimator,
)
from .experiments import (
    bootstrap_ci,
    identifiability_report,
    run_estimation_experiment,
    run_experiment,
)
from .metrics import (
    CERTIFICATE_DEFAULTS,
    Evaluator,
    ODCertifier,
    marginal_cost_tolls,
    marginal_costs,
    nrmse,
    price_of_anarchy,
    rmse,
    tolled_network,
)
from .models import (
    MODEL_REGISTRY,
    AlgorithmBModel,
    AllOrNothingModel,
    BiconjugateFrankWolfeModel,
    CallableModel,
    ConjugateFrankWolfeModel,
    DialSUEModel,
    ElasticDemandFWModel,
    FrankWolfeModel,
    GradientProjectionModel,
    LearnedSurrogateModel,
    MSAModel,
    SueProbitMsaModel,
    SystemOptimumModel,
    TapasModel,
    TrafficAssignmentModel,
    register_model,
)

__version__ = "0.2.0"

__all__ = [
    "Budget",
    "BudgetCoords",
    "Capabilities",
    "ContaminationError",
    "Demand",
    "ElasticDemand",
    "FactorSpec",
    "FlowState",
    "Network",
    "ReferenceSolution",
    "ResultBundle",
    "RngBundle",
    "Scenario",
    "Trace",
    "braess_scenario",
    "load_scenario",
    "two_route_scenario",
    "elastic_two_route_scenario",
    "run_experiment",
    "run_estimation_experiment",
    "identifiability_report",
    "bootstrap_ci",
    "Evaluator",
    "ODCertifier",
    "CERTIFICATE_DEFAULTS",
    "ESTIMATOR_REGISTRY",
    "ODEstimator",
    "register_estimator",
    "CallableEstimator",
    "EstimationTask",
    "ODTrace",
    "ODState",
    "ODResultBundle",
    "PriorBaseline",
    "GLSEstimator",
    "SpiessEstimator",
    "SPSAEstimator",
    "VZWEntropyEstimator",
    "marginal_costs",
    "marginal_cost_tolls",
    "nrmse",
    "price_of_anarchy",
    "rmse",
    "tolled_network",
    "MODEL_REGISTRY",
    "AlgorithmBModel",
    "AllOrNothingModel",
    "BiconjugateFrankWolfeModel",
    "CallableModel",
    "ConjugateFrankWolfeModel",
    "DialSUEModel",
    "ElasticDemandFWModel",
    "FrankWolfeModel",
    "GradientProjectionModel",
    "LearnedSurrogateModel",
    "MSAModel",
    "SueProbitMsaModel",
    "SystemOptimumModel",
    "TapasModel",
    "TrafficAssignmentModel",
    "register_model",
    "__version__",
]
